GET http://localhost:8080/all-movies

###
POST http://localhost:8080/add-movie
Content-Type: application/json 

{
    "titulo": "O Senhor dos Anéis: A Sociedade do Anel",
"genero": "Fantasia",
"duracao": "178",
"classificacao_etaria": "12"
}

###
DELETE http://localhost:8080/delete-movie/4

###
PUT http://localhost:8080/update-movie/4
Content-Type: application/json

{
    "titulo": "O espetacular Homem-Aranha",
    "genero": "Ação",
    "duracao": "125",
    "classificacao_etaria": "12"
}